name: 'chronic_conditions'
version: '0.1.2'
config-version: 2
profile: 'default'


vars:
  condition: "{{ var('chronic_conditions_condition_override', var('core_condition_override', ref('claims_preprocessing__condition'))) }}"
  encounter: "{{ var('chronic_conditions_encounter_override', var('core_encounter_override', ref('claims_preprocessing__encounter'))) }}"
  prescription: "{{ var('chronic_conditions_prescription_override', var('core_prescription_override', ref('claims_preprocessing__prescription'))) }}"
  procedure: "{{ var('chronic_conditions_procedure_override', var('core_procedure_override', ref('claims_preprocessing__procedure'))) }}"


model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  chronic_conditions:
    +materialized: table
