name: 'chronic_conditions'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# Configuration required for CLI users.  Cloud users can leave as 'default'
profile: 'default'

vars:
#
#  input_database: tuva               # configuration required
#                                     # name of the database where sources
#                                     # feeding this project are stored
#
#  input_schema: core                 # configuration required
#                                     # name of the schema where sources
#                                     # feeding this project is stored
#
#  output_database: tuva              # configuration required
#                                     # name of the database where output of
#                                     # this project should be written
#
#  output_schema: chronic_conditions  # configuration required
#                                     # name of the schema where output of this
#                                     # project should be written

  condition: "{% if project_name == 'chronic_conditions' %}{{ source('core','condition') }}{% else %}{{ ref('claims_preprocessing__condition') }}{% endif %}"
  encounter: "{% if project_name == 'chronic_conditions' %}{{ source('core','encounter') }}{% else %}{{ ref('claims_preprocessing__encounter') }}{% endif %}"
  medication: "{% if project_name == 'chronic_conditions' %}{{ source('core','medication') }}{% else %}{{ ref('claims_preprocessing__medication') }}{% endif %}"
  procedure: "{% if project_name == 'chronic_conditions' %}{{ source('core','procedure') }}{% else %}{{ ref('claims_preprocessing__procedure') }}{% endif %}"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
